rule("configure")
    add_deps("win.sdk.resource")
    on_config(function(target)
        import("core.base.semver")
        import("core.project.depend")
        import("core.project.project")
    end)
